from typing import Any, Literal, Optional, Union

__version__: str

class WorklistItem:
    @property
    def study_uid(self) -> str: ...
    @property
    def study_uid_origin(self) -> str: ...
    @property
    def warnings(self) -> list[str]: ...
    def to_bytes(self) -> bytes: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_keyword_dict(self) -> dict[str, Any]: ...

def worklist_item(
    message: Union[Any, bytes, str],  # hl7kit.Message, or the message text
    uid_policy: Literal["dcm4che", "random", "refuse"] = "dcm4che",
    length_policy: Literal["refuse", "truncate"] = "refuse",
    default_station_ae: Optional[str] = None,
    charset: Optional[str] = None,
) -> WorklistItem: ...
