from typing import Any, Optional, Sequence, Union

__version__: str

class ParseError(ValueError): ...

class StudyUid:
    value: str
    source: str  # "IPC-3.1" | "ZDS-1.1" | "OBX-110180"

class Order:
    patient_id: Optional[str]
    accession_number: Optional[str]
    requested_procedure_id: Optional[str]
    scheduled_procedure_step_id: Optional[str]
    study_uid: Optional[StudyUid]
    warnings: list[str]
    sources: dict[str, str]
    spans: dict[str, tuple[int, int]]
    def to_dict(self) -> dict[str, Any]: ...

class Message:
    @property
    def message_type(self) -> Optional[str]: ...
    @property
    def control_id(self) -> Optional[str]: ...
    @property
    def version(self) -> Optional[str]: ...
    @property
    def warnings(self) -> list[str]: ...
    def get(self, path: str) -> Optional[str]: ...
    def __getitem__(self, path: str) -> str: ...
    def span(self, path: str) -> Optional[tuple[int, int]]: ...
    def segments(self) -> list[str]: ...
    def order(self) -> Optional[Order]: ...
    def raw(self) -> bytes: ...

def parse(data: Union[bytes, str]) -> Message: ...
def parse_many(items: Sequence[bytes]) -> list[Message]: ...
